name: ai-chatbot-dev
services:
  mongodb:
    image: mongo:4.2.20
    hostname: mongodb
    volumes:
      - mongodbdata:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: backend
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        fastapi run --host=0.0.0.0 --reload --port=8080
    environment:
      APPLICATION_ENV: Development
      MONGODB_HOST: mongodb://mongodb:27017
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/ai-chatbox/backend
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/app:/usr/src/ai-chatbox/frontend/app
      - ./frontend/public:/usr/src/ai-chatbox/frontend/public
    restart: always
    ports:
      - 3000:3000

volumes:
  mongodbdata: